[mypy]
python_version = 3.11

# equilíbrio: útil sem ser chato demais
warn_return_any = True
warn_unused_configs = True

# evita poluição com libs sem tipagem
ignore_missing_imports = True

# melhora qualidade sem ser extremo
check_untyped_defs = True
disallow_incomplete_defs = True

# saída mais legível
pretty = True

[mypy-bs4.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy]
mypy_path = .
